name: highload

include:
 - patroni/docker-compose.yml
 - redis/docker-compose.yml
 - citus/docker-compose.yml
 - rabbitmq/docker-compose.yml 

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      # PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5      
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # volumes:
       # - ./data:/var/lib/postgresql/data 
    ports:
      - 6543:5432
    profiles: [postgres]      
  
  api: &api
    build: 
      context: ./..
      dockerfile: ./src/Otus.Highload.Api/Dockerfile
    image: highload-api
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=User ID=${PG_USERNAME};Password=${PG_PASSWORD};Host=${PG_HOST};Port=${PG_PORT};Database=${PG_USERNAME};Pooling=true;
      - ConnectionStrings__RabbitMQ=host=host.docker.internal;username=${RABBITMQ_DEFAULT_USER};password=${RABBITMQ_DEFAULT_PASS}
      - Dialogs__Url=http://api-dialogs
    ports:
      - 5000:80
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
    profiles: [postgres]      
    depends_on:
      db:
        condition: service_healthy
        
  api-dialogs: &api-dialogs
    build: 
      context: ./..
      dockerfile: ./src/Otus.Highload.Dialogs.Api/Dockerfile
    image: highload-api-dialogs
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Redis=host.docker.internal
    ports:
      - 5001:80
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
    profiles: [postgres]
    depends_on:
      redis:
        condition: service_started      
        
  ws-client:
    build: 
      context: ./..
      dockerfile: ./src/Otus.Highload.ClientWebSocket/Dockerfile
    image: highload-ws-client
    environment:
      - ConnectionStrings__Server=host.docker.internal:5000 
    depends_on:
      api:
        condition: service_healthy        
        
  api-citus:
    <<: *api    
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=User ID=${PG_USERNAME};Password=${PG_PASSWORD};Host=${PG_HOST};Port=${PG_PORT};Database=${PG_USERNAME};Pooling=true;
    profiles: [citus]  
    depends_on:
      master:
        condition: service_healthy     

  api-patroni:
    <<: *api
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=User ID=${PG_USERNAME};Password=${PG_PASSWORD};Host=${PG_HOST};Port=${PG_PORT};Database=${PG_USERNAME};Pooling=true;
      - ConnectionStrings__ReadOnly=User ID=${PG_USERNAME};Password=${PG_PASSWORD};Host=${PG_HOST};Port=${PG_SLAVE_PORT};Database=${PG_USERNAME};Pooling=true; 
    profiles: [patroni]  
    depends_on:
      haproxy:
        condition: service_healthy     
  
  data-loader: &loader
    image: bledig/alpine-psqlclient:3
    command: psql postgresql://${PG_USERNAME}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_USERNAME}  -a -f "/src/import_script.sql"
    volumes:
       - ./loader/import_script.sql:/src/import_script.sql 
       - ./loader/users_202503291621.zip:/src/users.zip
       - ./loader/user_friends_202503091840.zip:/src/user_friends.zip       
       - ./loader/posts_202503091841.zip:/src/posts.zip
       - ./loader/dialogs_202503151919.zip:/src/dialogs.zip
    depends_on:
      api:
        condition: service_healthy
    profiles: [postgres]          

  data-loader-citus:
    <<: *loader
    depends_on:
      api-citus:
        condition: service_healthy
    profiles: [citus]     
    
  data-loader-patroni:
    <<: *loader
    depends_on:
      api-citus:
        condition: service_healthy
    profiles: [patroni]             
  
  # faker-users-table:
    # build: 
      # context: ./../tools/postgresql_faker
      # dockerfile: Dockerfile  
    # image: postgres-faker
    # deploy:
      # mode: replicated
      # replicas: 10    
    # environment:  
      # TABLE: ${FAKER_USERS_TABLE}
      # INTERVAL: ${FAKER_INTERVAL}
      # LOOPS: ${FAKER_USERS_LOOPS}
      # ROWS_NUM: ${FAKER_USERS_ROWS_NUM}
      # LOCALE: ${FAKER_LOCALE}     
      # IS_PROD: ${FAKER_IS_PROD}
      # PG_HOST: ${PG_HOST}
      # PG_PORT: ${PG_PORT}
      # PG_USER: ${PG_USERNAME}
      # PG_DATABASE: ${PG_USERNAME}
      # PG_PASSWORD: ${PG_PASSWORD}
    # volumes:
       # - ./faker/users_metadata.json:/home/app/examples/metadata.json
    # depends_on:
      # db:
        # condition: service_healthy       
    