name: highload

include:
 - patroni/docker-compose.yml
 - redis/docker-compose.yml 

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      # PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5      
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # volumes:
       # - ./data:/var/lib/postgresql/data 
    ports:
      - 6543:5432
    profiles: [postgres]      
  
  api: &api
    build: 
      context: ./..
      dockerfile: ./src/Otus.Highload.Api/Dockerfile
    image: highload-api
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=User ID=${PG_USERNAME};Password=${PG_PASSWORD};Host=${PG_HOST};Port=${PG_PORT};Database=${PG_USERNAME};Pooling=true;
      - ConnectionStrings__Redis=host.docker.internal
    ports:
      - 5000:80
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
    profiles: [postgres]      
    depends_on:
      db:
        condition: service_healthy     

  api-highload:
    <<: *api
    container_name: api-highload
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=User ID=${PG_USERNAME};Password=${PG_PASSWORD};Host=${PG_HOST};Port=${PG_PORT};Database=${PG_USERNAME};Pooling=true;
      - ConnectionStrings__ReadOnly=User ID=${PG_USERNAME};Password=${PG_PASSWORD};Host=${PG_HOST};Port=${PG_SLAVE_PORT};Database=${PG_USERNAME};Pooling=true; 
    profiles: [patroni]  
    depends_on:
      haproxy:
        condition: service_healthy     
  
  data-loader: &loader
    image: bledig/alpine-psqlclient:3
    container_name: data-loader
    command: psql postgresql://${PG_USERNAME}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_USERNAME}  -a -f "/src/import_script.sql"
    volumes:
       - ./loader/import_script.sql:/src/import_script.sql 
       - ./loader/users_202502091738.zip:/src/users.zip
       - ./loader/user_friends_202503091840.zip:/src/user_friends.zip       
       - ./loader/posts_202503091841.zip:/src/posts.zip
    depends_on:
      api:
        condition: service_healthy          
    profiles: [postgres]         

  users-loader-highload:
    <<: *loader
    container_name: users-loader-highload
    depends_on:
      api-highload:
        condition: service_started
    profiles: [patroni]         
  
  # faker-users-table:
    # build: 
      # context: ./../tools/postgresql_faker
      # dockerfile: Dockerfile  
    # image: postgres-faker
    # deploy:
      # mode: replicated
      # replicas: 10    
    # environment:  
      # TABLE: ${FAKER_USERS_TABLE}
      # INTERVAL: ${FAKER_INTERVAL}
      # LOOPS: ${FAKER_USERS_LOOPS}
      # ROWS_NUM: ${FAKER_USERS_ROWS_NUM}
      # LOCALE: ${FAKER_LOCALE}     
      # IS_PROD: ${FAKER_IS_PROD}
      # PG_HOST: ${PG_HOST}
      # PG_PORT: ${PG_PORT}
      # PG_USER: ${PG_USERNAME}
      # PG_DATABASE: ${PG_USERNAME}
      # PG_PASSWORD: ${PG_PASSWORD}
    # volumes:
       # - ./faker/users_metadata.json:/home/app/examples/metadata.json
    # depends_on:
      # db:
        # condition: service_healthy       
    