name: postgres-faker
services:
  faker:
    build: 
      context: .
      dockerfile: Dockerfile  
    image: postgres-faker
    container_name: faker
    environment:
      LOOPS: ${FAKER_LOOPS}    
      TABLE: ${FAKER_TABLE}
      ROWS_NUM: ${FAKER_ROWS_NUM}
      INTERVAL: ${FAKER_INTERVAL}
      LOCALE: ${FAKER_LOCALE}
      METADATA: ${FAKER_METADATA}      
      IS_PROD: ${FAKER_IS_PROD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USERNAME}
      PG_DATABASE: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}  