{
 "title": "Dialog Dashboard",
 "panels": [
  {
   "title": "Message added Total (Rate)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(message_added_Messages_total[1m])) by (to_user_id)",
     "legendFormat": "{{to_user_id}}"
    }
   ]
  },
  {
   "title": "Message error Total (Rate)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(message_error_Messages_total[1m])) by (user_id)",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Message Duration (Percentiles)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(users_message_duration_Messages_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(users_message_duration_Messages_bucket[5m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(users_message_duration_Messages_bucket[5m])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}