services:
    rabbitmq3:
      container_name: rabbitmq
      image: rabbitmq:3-management
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-user}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-password}
      ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'