global:
  scrape_interval: 5s

scrape_configs:
  # Сбор метрик самого Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Сбор метрик api-dialogs
  - job_name: "api-dialogs"
    static_configs:
      - targets: ["api-dialogs:5067"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "/etc/prometheus/alert_rules.yml"
